[package]
name = "boron_target"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
strum = { workspace = true }
inkwell = { workspace = true }

[lints]
workspace = true
