[package]
name = "boron"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Boron compiler"

[dependencies]
clap = { workspace = true }
boron_cli = { workspace = true }
boron_core = { workspace = true }

[lints]
workspace = true

