[package]
name = "zirael_target"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
strum = { workspace = true }

[lints]
workspace = true
